# Site settings
title: 取栗藏  # 博客名字
header-img: "img/sakura.jpg"
tagline: "cn"  
description: "技术，产品，经济，政治，观点，新思路"  # 一句话描述你的博客
baseurl: "http://horaccefeng.com"
url: "http://horaccefeng.com"  # 此处填写你的博客地址 


# About/contact
owner: 
  name: "小木君" # 填写作者信息：名字
  email: yenitsed3@gmail.com # 填写作者信息：邮箱
  bio: "不分对错，不论立场，只求观点" # 填写作者信息：博客描述


# Data
gavatar: img/favicon.ico # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.ico # 浏览器地址栏小图标，可自定义更改

github_username: HoracceFeng
zhihu_username: feng-xiao-mu-24
CSDN_username: u014469896
douban_username:  
twitter_username: 
facebook_username: 
weibo_username: 


# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8    ## display number of blog posts
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","ArticleHub"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "小木君" # 你的名字
      header-img: "img/sakura.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name : HoracceFeng # 填写你的 disqus id
  disqus :
      short_name : HoracceFeng # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics: UA-137859383-1 # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
